name: Build
on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-maven
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/local-unit-tests
  gradle-emulator-test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/gradle-emulator-tests

